# syntax=docker/dockerfile:1

ARG NODE_VERSION=24.13.0

FROM node:${NODE_VERSION}-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache \
  curl \
  postgresql-client

COPY package*.json ./
RUN npm install
RUN npm install -g ts-node typescript

CMD ["npm", "run", "start:dev"]
